# Generated by Django 4.2.1 on 2023-06-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresSourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('port', models.IntegerField()),
                ('schemas', models.TextField()),
                ('database', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('ssl', models.BooleanField()),
                ('ssl_mode', models.CharField(choices=[('disable', 'Disable'), ('allow', 'Allow'), ('prefer', 'Prefer'), ('require', 'Require'), ('verify-ca', 'Verify Ca'), ('verify-full', 'Verify Full')], max_length=20)),
                ('tunnel_method', models.CharField(choices=[('NO_TUNNEL', 'No Tunnel'), ('SSH_TUNNEL', 'Ssh Tunnel'), ('SSH_TUNNEL_WITH_PASSWORD', 'Ssh Tunnel With Password'), ('SSH_TUNNEL_WITH_KEY', 'Ssh Tunnel With Key'), ('SSH_TUNNEL_WITH_AGENT', 'Ssh Tunnel With Agent'), ('SSH_TUNNEL_WITH_PASSWORD_AND_KEY', 'Ssh Tunnel With Password And Key')], max_length=40)),
                ('replication_method', models.CharField(choices=[('Standard', 'Standard'), ('Logical', 'Logical')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SourceConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
