# Generated by Django 4.2.1 on 2023-06-27 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('billing_plan', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('is_suspended', models.BooleanField(default=False, null=True)),
                ('is_demo', models.BooleanField(default=False, null=True)),
                ('is_trial', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.TextField(null=True)),
                ('api_key', models.TextField(null=True)),
                ('email_verified', models.BooleanField(default=False, null=True)),
                ('email_verification_sent', models.BooleanField(default=False, null=True)),
                ('email_verified_at', models.DateTimeField(null=True)),
                ('welcome_email_sent', models.BooleanField(default=False, null=True)),
                ('welcome_email_sent_at', models.DateTimeField(null=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('is_suspended', models.BooleanField(default=False, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dashboard.orgaccount')),
            ],
        ),
    ]
