# Generated by Django 4.2.1 on 2023-07-14 23:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_dashboard', '0006_mljob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('inbound_flows', models.ManyToManyField(related_name='inbound_flows', to='web_dashboard.dataflow')),
                ('ml_jobs', models.ManyToManyField(to='web_dashboard.mljob')),
                ('outbound_flows', models.ManyToManyField(related_name='outbound_flows', to='web_dashboard.dataflow')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dashboard.useraccount')),
                ('views', models.ManyToManyField(to='web_dashboard.dataview')),
            ],
        ),
    ]
