# Generated by Django 4.2.1 on 2023-07-14 23:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_dashboard', '0007_pipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('data_flows', models.ManyToManyField(to='web_dashboard.dataflow')),
                ('data_stores', models.ManyToManyField(to='web_dashboard.datastore')),
                ('data_views', models.ManyToManyField(to='web_dashboard.dataview')),
                ('ml_jobs', models.ManyToManyField(to='web_dashboard.mljob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dashboard.useraccount')),
                ('pipelines', models.ManyToManyField(to='web_dashboard.pipeline')),
            ],
        ),
    ]
