# Generated by Django 4.2.1 on 2023-07-17 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_dashboard', '0008_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgaccount',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='owner',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgaccount',
            name='billing_plan',
            field=models.TextField(default='free'),
        ),
        migrations.AlterModelTable(
            name='orgaccount',
            table='anm_orgaccount',
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='anm_useraccount',
        ),
    ]
