# Generated by Django 4.2.1 on 2023-06-27 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_dashboard', '0003_datastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('topic', models.TextField(null=True)),
                ('backend', models.TextField(null=True)),
                ('backend_config', models.JSONField(null=True)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_store', to='web_dashboard.datastore')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dashboard.useraccount')),
                ('source_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_store', to='web_dashboard.datastore')),
            ],
        ),
    ]
