# Generated by Django 4.2.1 on 2023-06-27 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_dashboard', '0004_dataflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('query', models.TextField(null=True)),
                ('data_flows', models.ManyToManyField(to='web_dashboard.dataflow')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dashboard.useraccount')),
            ],
        ),
    ]
