# Generated by Django 4.2.1 on 2023-07-14 22:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_dashboard', '0005_dataview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('backend', models.TextField(null=True)),
                ('backend_config', models.JSONField(null=True)),
                ('topic', models.TextField(null=True)),
                ('data_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dashboard.dataview')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dashboard.useraccount')),
            ],
        ),
    ]
